# Numpy and Pandas

In [1]:
import numpy as np

## 1. Numpy random

`np.random.choice` generates a random sample from a given 1-D array

In [2]:
np.random.choice(a=['a', 'b', 'c', 'd', 'e', 'f'], size=60, replace=True)

array(['f', 'a', 'b', 'e', 'e', 'd', 'f', 'e', 'd', 'f', 'f', 'e', 'a',
       'e', 'f', 'a', 'f', 'a', 'e', 'd', 'b', 'd', 'b', 'c', 'd', 'd',
       'e', 'f', 'd', 'a', 'b', 'd', 'a', 'e', 'f', 'a', 'a', 'a', 'c',
       'f', 'c', 'a', 'c', 'd', 'f', 'a', 'f', 'e', 'e', 'd', 'd', 'e',
       'f', 'b', 'b', 'a', 'f', 'e', 'e', 'c'], dtype='<U1')

In [3]:
np.random.choice(a=['a', 'b', 'c', 'd'], p=[0.1, 0.1, 0.7, 0.1], size=100)

array(['c', 'c', 'c', 'b', 'd', 'd', 'c', 'c', 'b', 'c', 'c', 'd', 'c',
       'c', 'c', 'c', 'c', 'a', 'a', 'c', 'c', 'd', 'c', 'c', 'c', 'c',
       'c', 'd', 'c', 'c', 'c', 'c', 'd', 'c', 'a', 'b', 'c', 'c', 'c',
       'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'b', 'c', 'c',
       'c', 'c', 'd', 'b', 'c', 'c', 'c', 'c', 'a', 'c', 'a', 'c', 'c',
       'a', 'c', 'c', 'c', 'c', 'c', 'a', 'd', 'c', 'a', 'b', 'c', 'c',
       'c', 'c', 'd', 'a', 'c', 'c', 'c', 'c', 'b', 'c', 'a', 'c', 'c',
       'c', 'c', 'd', 'c', 'd', 'c', 'c', 'c', 'c'], dtype='<U1')

In [4]:
np.random.choice(a=np.arange(1, 101), size=100, replace=False)

array([ 33,  57,  80,  38,  69,  78,  47,  66,  18,  10,  53,  48,  94,
        40,  95,  34,  49,   5,  46,  35,  22,  15,  81,  70,  86,  55,
        23,  73,  76,  68,  11,  30,  50,   6,  13,  41,  71,  59,  54,
        65,  44,  31,  20,  36,  92,  12,  60,  79,  58,  63,  99,  24,
        90,  97,   8,  32,  27,  93,  28,  98,  67,  37,  84,  56,   2,
        77,  17,  96,  42,  85, 100,  21,  14,  83,   7,  87,  88,  52,
        82,  26,  45,  43,  16,  51,   3,  89,  29,   9,  25,  19,  39,
         4,  74,  62,  91,  75,  64,   1,  72,  61])

In [5]:
# similar to (note that this changes the array in place):
x = np.arange(1, 101)
np.random.shuffle(x)
x

array([ 18,  19,  15,  35,   4,  81,  50,  97,  74,  66,  24,  44,  13,
        55,  29,  91,  93,  30,  36,  33,  41,  85,  62,  78,  83, 100,
        63,  82,  11,  14,  12,  39,   5,   6,  16,  49,  86,  21,  68,
        70,  25,   1,  10,  47,  73,  22,   7,  42,  94,   9,  46,  17,
        87,  61,  99,  45,  54,  20,  84,  56,  32,  31,  95,  67,  23,
        77,  75,  98,  52,  64,  43,  60,  37,  65,  59,  80,  69,  90,
        58,  28,  96,  89,  92,  53,  79,  34,  71,  40,  27,   3,  26,
        48,  72,  38,  51,  88,  76,   8,   2,  57])

In [6]:
# to reorder x (note that this does not change the array in place)
x = np.sort(x)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
# 20 numbers between 0 and 10
np.random.randint(0, 10, size=20)

array([8, 1, 1, 0, 7, 0, 4, 8, 3, 8, 4, 2, 3, 9, 8, 1, 3, 2, 0, 5])

We can also sample from distributions:

In [8]:
np.random.uniform(low=0, high=10, size=20)

array([3.01461133, 3.53452123, 2.34628291, 7.28188161, 6.26202108,
       9.72303743, 3.67161115, 5.52337279, 9.99065145, 5.26066856,
       2.63291006, 4.52908421, 8.70542131, 7.76579581, 5.12511977,
       1.57069707, 6.97322372, 1.99764776, 6.4342924 , 6.61895866])

In [9]:
np.random.normal(loc=0, scale=1, size=10)

array([-0.03259565, -0.21107958, -0.72808715,  0.04759005, -0.16331167,
       -1.09012108, -0.1619874 ,  1.05896103,  0.40838606, -2.16232633])

In [10]:
np.random.normal(loc=[-10, 0, 10], scale=1)

array([-10.0544399 ,  -0.67101151,  10.32394888])

In [11]:
np.random.binomial(n=1, p=.8, size=50)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1])

In [12]:
np.random.binomial(n=1, p=[.6, .8, .1, .2])

array([0, 0, 0, 0])

## 2. Tiling and repeating arrays

In [13]:
letters = np.array(['A', 'B', 'C'])
colors = np.array(['red', 'blue', 'grey'])

In [14]:
colors = np.repeat(colors, repeats=3)
colors

array(['red', 'red', 'red', 'blue', 'blue', 'blue', 'grey', 'grey',
       'grey'], dtype='<U4')

In [15]:
letters = np.tile(letters, reps=3)
letters

array(['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'], dtype='<U1')

In [16]:
colors + letters

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U4'), dtype('<U4')) -> dtype('<U4')

In [17]:
np.char.add(letters, colors)

array(['Ared', 'Bred', 'Cred', 'Ablue', 'Bblue', 'Cblue', 'Agrey',
       'Bgrey', 'Cgrey'], dtype='<U5')

## 3. Creating a pandas dataframe

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame({
    'letters': letters,
    'colors': colors,
    'stimuli': np.char.add(np.char.add(letters, "_"), colors)
             })

In [20]:
df

letters colors stimuli
0       A    red   A_red
1       B    red   B_red
2       C    red   C_red
3       A   blue  A_blue
4       B   blue  B_blue
5       C   blue  C_blue
6       A   grey  A_grey
7       B   grey  B_grey
8       C   grey  C_grey

In [21]:
df['letters']

0    A
1    B
2    C
3    A
4    B
5    C
6    A
7    B
8    C
Name: letters, dtype: object

In [22]:
df['trial'] = np.arange(1, 10)
df['participant'] = 1

In [23]:
df

letters colors stimuli  trial  participant
0       A    red   A_red      1            1
1       B    red   B_red      2            1
2       C    red   C_red      3            1
3       A   blue  A_blue      4            1
4       B   blue  B_blue      5            1
5       C   blue  C_blue      6            1
6       A   grey  A_grey      7            1
7       B   grey  B_grey      8            1
8       C   grey  C_grey      9            1

In [24]:
df.shape

(9, 5)

In [25]:
df['block'] = 1
df

letters colors stimuli  trial  participant  block
0       A    red   A_red      1            1      1
1       B    red   B_red      2            1      1
2       C    red   C_red      3            1      1
3       A   blue  A_blue      4            1      1
4       B   blue  B_blue      5            1      1
5       C   blue  C_blue      6            1      1
6       A   grey  A_grey      7            1      1
7       B   grey  B_grey      8            1      1
8       C   grey  C_grey      9            1      1

In [26]:
df.loc[(df.trial > 3) & (df.trial < 7), 'block'] = 2
df.loc[df.trial > 6, 'block'] = 3
df

letters colors stimuli  trial  participant  block
0       A    red   A_red      1            1      1
1       B    red   B_red      2            1      1
2       C    red   C_red      3            1      1
3       A   blue  A_blue      4            1      2
4       B   blue  B_blue      5            1      2
5       C   blue  C_blue      6            1      2
6       A   grey  A_grey      7            1      3
7       B   grey  B_grey      8            1      3
8       C   grey  C_grey      9            1      3

#### Filling-in an empty dataframe

In [27]:
df = pd.DataFrame([]) # create an empty dataframe
df

Empty DataFrame
Columns: []
Index: []

In [28]:
df = df.append({'rt': 2, 'choice': 'l', 'trial': 1, 'reward': 34}, ignore_index=True) # record some responses

In [29]:
df

choice  reward   rt  trial
0      l    34.0  2.0    1.0

In [30]:
df = df.append({'rt': 2.1, 'choice': 'k', 'trial': 2, 'reward': 36}, ignore_index=True) # record some responses

In [31]:
df

choice  reward   rt  trial
0      l    34.0  2.0    1.0
1      k    36.0  2.1    2.0

In [32]:
responses = pd.Series([2, 'l', 3, 20],index=['rt', 'choice', 'trial', 'reward'])

In [33]:
responses

rt         2
choice     l
trial      3
reward    20
dtype: object

In [34]:
df = df.append(responses, ignore_index=True)

In [35]:
df

choice  reward   rt  trial
0      l    34.0  2.0    1.0
1      k    36.0  2.1    2.0
2      l    20.0  2.0    3.0

#### Save the dataframe to file

In [36]:
df.to_csv('data.csv') # save to file

#### Shuffling a dataframe

In [37]:
df = pd.DataFrame({'image_number': np.arange(1, 11), 'difficulty': np.repeat(['easy','hard'], 5)})
df

image_number difficulty
0             1       easy
1             2       easy
2             3       easy
3             4       easy
4             5       easy
5             6       hard
6             7       hard
7             8       hard
8             9       hard
9            10       hard

In [38]:
df.sample(frac=1) # shaffle across all trials

image_number difficulty
0             1       easy
8             9       hard
9            10       hard
7             8       hard
5             6       hard
3             4       easy
4             5       easy
1             2       easy
6             7       hard
2             3       easy

In [39]:
df = df.sample(frac=1).reset_index(drop=True)
df

image_number difficulty
0             6       hard
1             3       easy
2            10       hard
3             9       hard
4             4       easy
5             1       easy
6             8       hard
7             2       easy
8             7       hard
9             5       easy

In [40]:
df.groupby(['difficulty']).apply(lambda x: x.sample(frac=1)).reset_index(drop=True) # shaffle within condition

image_number difficulty
0             4       easy
1             1       easy
2             5       easy
3             2       easy
4             3       easy
5             7       hard
6             8       hard
7             9       hard
8            10       hard
9             6       hard

## Exercises

1. Create a dataframe called `stimuli`. The first column should be called `participant`, the second column `trial`, and the third one `condition`. There should be 10 trials per condition, and 3 conditions for each participant, and 4 participants. Therefore, in total the dataframe should have 4*3*10=120 rows, and 3 columns. The participant numbers should go from 1 to 4, the conditions should be labelled `['low', 'med', 'high']`, and the trials should be numbered from 1 to 30. The order of the condition should be randomized within participant.
2. Add a column called `probability`, which is equal to .1 when the condition is `low`, .5 when it's `med`, and .9 when it's 'high'.
3. Create a new dataframe called `data`, that is a copy of the `stimuli` dataframe (using the `.copy()` attribute, as in `new_dataframe = old_dataframe.copy()`). Add to `data` a column called `choice`, by generating data from a binomial distribution with parameters `n=1` and the probability that is in the probability column of each trial.

**Send me your solutions** before the end of this Friday (at laura.fontanesi@unibas.ch).

**NOTE**: Do not send me a notebook but export it to a Python script first: `File> Export notebook as… > Export as executable script`