# Intro to built-in data types and numpy arrays

First of all, activate the `psychopy` conda envirornment (from the Terminal or Anaconda Prompt: `conda activate psychopy`, or from the Anaconda navigator) and let's check that `numpy` is installed.

In [1]:
import numpy as np

## 1. Built-in Python types

Text and numeric types:

In [2]:
text = "ciao my name is Laura, sdalkghjdflkghj;akd93040989"

In [3]:
text

'ciao my name is Laura, sdalkghjdflkghj;akd93040989'

In [4]:
type(text)

str

In [5]:
number = 3
type(number)

int

In [6]:
another_number = 3.2
type(another_number)

float

Booleans are truth statements:

In [7]:
number > 3

False

In [8]:
a = (number < 3)

In [9]:
a

False

In [10]:
number <= 3

True

In [11]:
type(a)

bool

Sequences and mappings:

- List is a collection which is ordered and changeable. Allows duplicate members.
- Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
- Dictionary is a collection which is unordered and changeable. No duplicate members.

In [12]:
a_list = [1, 2, 3]
type(a_list)

list

In [13]:
a_list

[1, 2, 3]

In [14]:
a_tuple = (2, "b")
type(a_tuple)

tuple

In [15]:
a_dictionary = {"age": 25, "height": 180, "measurements": [8, 6, 15]}
type(a_dictionary)

dict

## 2. Lists

In [16]:
list_of_int = [1, 2, 3, 4]
list_of_int

[1, 2, 3, 4]

In [17]:
list_of_str = ['a', 'b', 'c', 'defgh']
list_of_str

['a', 'b', 'c', 'defgh']

In [18]:
list_of_bool = [True, False, True, True]
list_of_bool

[True, False, True, True]

In [19]:
list_of_float = [0.1, 1, 2.1, 3.4]
list_of_float

[0.1, 1, 2.1, 3.4]

In [20]:
list_of_int[0] # first element of a list

1

In [21]:
type(list_of_bool)

list

In [22]:
type(list_of_float[1]), type(list_of_float[2]) # list can contain different data types

(int, float)

In [23]:
['a', 1, [1, 2, 3]]

['a', 1, [1, 2, 3]]

In [24]:
len(list_of_float) # how many elements are in this list?

4

In [25]:
list_of_float*3 # stack the same list

[0.1, 1, 2.1, 3.4, 0.1, 1, 2.1, 3.4, 0.1, 1, 2.1, 3.4]

In [26]:
list_of_float + list_of_bool + list_of_float # stack different lists

[0.1, 1, 2.1, 3.4, True, False, True, True, 0.1, 1, 2.1, 3.4]

In [27]:
list_of_float # the original does not change!

[0.1, 1, 2.1, 3.4]

In [28]:
se = list_of_float*3 

In [29]:
se

[0.1, 1, 2.1, 3.4, 0.1, 1, 2.1, 3.4, 0.1, 1, 2.1, 3.4]

In [30]:
list_of_float

[0.1, 1, 2.1, 3.4]

In [31]:
list_of_float.append(list_of_bool) # add elements at the end

In [32]:
list_of_float # the original changed!

[0.1, 1, 2.1, 3.4, [True, False, True, True]]

In [33]:
len(list_of_float) # we appended a list as an element

5

In [34]:
for i in list_of_str: # now we append every element one at a time
    list_of_int.append(i)

In [35]:
list_of_int

[1, 2, 3, 4, 'a', 'b', 'c', 'defgh']

In [36]:
list_of_int.sort() # you cannot sort the list when the elements are of different type though

TypeError: '<' not supported between instances of 'str' and 'int'

In [37]:
list_of_int = [2, 15, 6, 1]

In [38]:
list_of_int.sort()

In [39]:
list_of_int

[1, 2, 6, 15]

In [40]:
list_of_int.reverse() # reverse the order!
list_of_int

[15, 6, 2, 1]

In [41]:
list_of_int.remove(15) # remove a specific element
list_of_int

[6, 2, 1]

In [42]:
list_of_int.insert(2, 34) # insert a specific element in a certain position
list_of_int

[6, 2, 34, 1]

In [43]:
list_of_int.pop(2) # remove a specific element in a certain position
list_of_int

[6, 2, 1]

## 3. Dictionaries

In [44]:
auto = {'model': 'PEUGEOT 308',
        'CHF': 10500,
        'where': 'Dietikon',
        'km': 86000,
        'fuel': 'diesel',
        'ccm': 1560
       }

In [45]:
auto.values()

dict_values(['PEUGEOT 308', 10500, 'Dietikon', 86000, 'diesel', 1560])

In [46]:
auto.keys()

dict_keys(['model', 'CHF', 'where', 'km', 'fuel', 'ccm'])

In [47]:
auto.items()

dict_items([('model', 'PEUGEOT 308'), ('CHF', 10500), ('where', 'Dietikon'), ('km', 86000), ('fuel', 'diesel'), ('ccm', 1560)])

In [48]:
for i in auto.items():
    print(type(i))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [49]:
for i in auto.keys():
    print(i)

model
CHF
where
km
fuel
ccm


In [50]:
for i in auto.keys():
    print(auto[i])

PEUGEOT 308
10500
Dietikon
86000
diesel
1560


In [51]:
len(auto) # how many items?

6

In [52]:
auto['model'] # get value corresponding to a key

'PEUGEOT 308'

In [53]:
auto['km'] = 90000 # change a value
auto

{'model': 'PEUGEOT 308',
 'CHF': 10500,
 'where': 'Dietikon',
 'km': 90000,
 'fuel': 'diesel',
 'ccm': 1560}

In [54]:
auto['color'] = 'blue' # add an item
auto

{'model': 'PEUGEOT 308',
 'CHF': 10500,
 'where': 'Dietikon',
 'km': 90000,
 'fuel': 'diesel',
 'ccm': 1560,
 'color': 'blue'}

In [55]:
'color' in auto # is a key in the dic?

True

In [56]:
auto.pop("CHF") # remove an item
auto

{'model': 'PEUGEOT 308',
 'where': 'Dietikon',
 'km': 90000,
 'fuel': 'diesel',
 'ccm': 1560,
 'color': 'blue'}

## 4. Creating a numpy array 

In [57]:
import numpy as np

In [58]:
np.array()

TypeError: Required argument 'object' (pos 1) not found

In [59]:
empty_list = []

In [60]:
len(empty_list)

0

In [61]:
first_array = np.array([])
first_array

array([], dtype=float64)

In [62]:
int_array = np.array([1, 2, 3, 4])
int_array

array([1, 2, 3, 4])

In [63]:
int_array.dtype

dtype('int64')

In [64]:
str_array = np.array(['a', 'b', 'c', 'd', 'e'])
str_array.dtype

dtype('<U1')

In [65]:
str_array = np.array(['aerf', 'B1', 'c', 'd', 'e'])
str_array.dtype

dtype('<U4')

In [66]:
type(int_array), type(first_array), type(str_array)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [67]:
int_array[0] # access the first element

1

In [68]:
more_dimensions = np.array([[1, 2, 3], [4.1, 5, 6]])
more_dimensions

array([[1. , 2. , 3. ],
       [4.1, 5. , 6. ]])

In [69]:
more_dimensions[0, 2] # access elements in a 2D array

3.0

In [70]:
more_dimensions[1, 0] = 4 # change an element
more_dimensions

array([[1., 2., 3.],
       [4., 5., 6.]])

In [71]:
more_dimensions.dtype # differently from lists, the elements of an array must all have same type

dtype('float64')

In [72]:
more_dimensions.astype(int) # change type

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
int_array.shape

(4,)

In [74]:
more_dimensions.shape

(2, 3)

Create arrays made of zeros or ones:

In [75]:
a = np.zeros(shape=(3, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
a*b # differently from lists, operations between arrays are math operations

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
a + b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
b*24

array([24., 24., 24., 24., 24., 24., 24., 24., 24., 24.])

In [80]:
a + 10 / 2

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

Create different kind of sequences:

In [81]:
np.arange(start=0, stop=11, step=2) # sequence of numbers from start to stop, every step

array([ 0,  2,  4,  6,  8, 10])

In [82]:
np.arange(1, 12, step=2)

array([ 1,  3,  5,  7,  9, 11])

In [83]:
np.linspace(start=1, stop=10, num=10) # sequence of num lenghts, between start and stop

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [84]:
np.linspace(start=0, stop=10, num=21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

## 5. Boolean indexing

In [85]:
c = np.arange(1, 101, 1).reshape(10, 10)
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [86]:
c > 45

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [87]:
c[c <= 10] = 0
c

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

## Exercises

- 1.1 Create a dictionary called `dog`, made of 5 meaningful items of your choice. Values should include: at least 1 integer, 1 list, 1 string.
- 1.2 Add an element to the list that you stored in the `dog` dictionary, and print the new dictionary.
- 1.3 Eliminate the item whose value was an integer, and print the new dictionary.
- 1.4 Add a new item, print the dictionary, and then delete it, and print it again.


- 2.1 Create a numpy array called `a`, of shape (10, 2), made of ones.
- 2.2 Create a numpy array called `b`, of shape (10, 1), made of zeros.
- 2.3 Add `a` to `b` and call their result `ab`.
- 2.4 Access the second element in the third row of `ab` and assign the value 100. Print the new `ab`.
- 2.5 Create a sequence called `c`, containing all multiples of 10 up to 200.
- 2.6 Create a sequence called `d`, containing all numbers from 0 to 2 with 2 decimals.

**Send me your solutions** before the end of this Friday (at laura.fontanesi@unibas.ch).

**NOTE**: Do not send me a notebook but simply a text file, named `wpa_2_Surname_Name.py` (with your own name and surname of course). To make it a bit clear, please write a comment to indicate which answer a specific chunk of code releated to, e.g.:

```
# exercise 1
a = 7 + 8
b = 8
c = a*b

# exercise 2
e = np.array([4, 5, 76])
f = np.append(e, [3, 4, 5])
```

## Solutions

### Exercise 1

- 1.1 Create a dictionary called `dog`, made of 5 meaningful items of your choice. Values should include: at least 1 integer, 1 list, 1 string.
- 1.2 Add an element to the list that you stored in the `dog` dictionary, and print the new dictionary.
- 1.3 Eliminate the item whose value was an integer, and print the new dictionary.
- 1.4 Add a new item, print the dictionary, and then delete it, and print it again.

In [88]:
dog = {
    'breed': 'Australian Shepherd',
    'pedigree': False,
    'gender': 'f',
    'age': 2,
    'height_jumps': [.6, 1.2, .8, 1.1, 1.5]
      }
dog['height_jumps'].append(1)
dog

{'breed': 'Australian Shepherd',
 'pedigree': False,
 'gender': 'f',
 'age': 2,
 'height_jumps': [0.6, 1.2, 0.8, 1.1, 1.5, 1]}

In [89]:
dog.pop('age')
dog

{'breed': 'Australian Shepherd',
 'pedigree': False,
 'gender': 'f',
 'height_jumps': [0.6, 1.2, 0.8, 1.1, 1.5, 1]}

In [90]:
dog['likes_apples'] = True
dog

{'breed': 'Australian Shepherd',
 'pedigree': False,
 'gender': 'f',
 'height_jumps': [0.6, 1.2, 0.8, 1.1, 1.5, 1],
 'likes_apples': True}

In [91]:
dog.pop('likes_apples')
dog

{'breed': 'Australian Shepherd',
 'pedigree': False,
 'gender': 'f',
 'height_jumps': [0.6, 1.2, 0.8, 1.1, 1.5, 1]}

### Exercise 2

- 2.1 Create a numpy array called `a`, of shape (10, 2), made of ones.
- 2.2 Create a numpy array called `b`, of shape (10, 1), made of zeros.
- 2.3 Add `a` to `b` and call their result `ab`.
- 2.4 Access the second element in the third row of `ab` and assign the value 100. Print the new `ab`.
- 2.5 Create a sequence called `c`, containing all multiples of 10 up to 200.
- 2.6 Create a sequence called `d`, containing all numbers from 0 to 2 with 2 decimals.

In [92]:
a = np.ones((10, 2))
b = np.zeros((10, 1))

In [93]:
ab = a + b
ab

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [94]:
ab[2, 1] = 100
ab

array([[  1.,   1.],
       [  1.,   1.],
       [  1., 100.],
       [  1.,   1.],
       [  1.,   1.],
       [  1.,   1.],
       [  1.,   1.],
       [  1.,   1.],
       [  1.,   1.],
       [  1.,   1.]])

In [95]:
c = np.arange(10, 201, 10)
c

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [96]:
d = np.arange(0, 2.01, .01)
d

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.