# Numpy and Pandas

In [1]:
import numpy as np

## 1. Numpy random

`np.random.choice` generates a random sample from a given 1-D array

In [2]:
np.random.choice(a=['a', 'b', 'c', 'd', 'e', 'f'], size=60, replace=True)

array(['d', 'f', 'c', 'd', 'f', 'c', 'f', 'e', 'a', 'e', 'b', 'e', 'f',
       'a', 'd', 'e', 'a', 'b', 'f', 'a', 'a', 'd', 'f', 'e', 'c', 'c',
       'a', 'a', 'a', 'e', 'd', 'a', 'c', 'f', 'c', 'b', 'c', 'f', 'd',
       'd', 'f', 'a', 'f', 'd', 'b', 'a', 'f', 'b', 'b', 'b', 'd', 'a',
       'a', 'c', 'c', 'b', 'a', 'f', 'c', 'e'], dtype='<U1')

In [3]:
np.random.choice(a=['a', 'b', 'c', 'd'], p=[0.1, 0.1, 0.7, 0.1], size=100)

array(['a', 'b', 'c', 'c', 'c', 'c', 'c', 'c', 'a', 'd', 'b', 'c', 'a',
       'd', 'c', 'b', 'c', 'c', 'c', 'c', 'c', 'd', 'a', 'c', 'c', 'c',
       'c', 'd', 'c', 'c', 'a', 'a', 'c', 'c', 'c', 'b', 'c', 'c', 'd',
       'a', 'c', 'c', 'c', 'd', 'a', 'c', 'c', 'a', 'c', 'b', 'c', 'c',
       'c', 'd', 'c', 'c', 'c', 'd', 'c', 'c', 'c', 'c', 'c', 'c', 'a',
       'c', 'c', 'c', 'a', 'c', 'c', 'a', 'b', 'c', 'c', 'c', 'c', 'c',
       'a', 'c', 'd', 'c', 'c', 'a', 'a', 'c', 'c', 'c', 'c', 'a', 'd',
       'c', 'c', 'c', 'c', 'd', 'c', 'd', 'c', 'b'], dtype='<U1')

In [4]:
np.random.choice(a=np.arange(1, 101), size=100, replace=False)

array([ 58,   4,  49,  62,  52,  51,  66,  82,  99,  85,  92,  56,  21,
        24,  76,  53,  23,  75,  13,  33,  35,  55,  10,  57,  87,  60,
        63,  43,  30,  36,  68,   9,  70,  69,  95,  19,  25,  17,  64,
        78,  50,  94,  47,  73,  86,  32,  16,   6,  46,  37,  88,  31,
       100,  26,  79,  11,  81,  34,  72,  44,  89,  39,  74,  71,  96,
        15,  48,   7,  67,   2,  80,  98,  22,  27,  18,   3,  41,  97,
        93,  54,  59,   5,  40,   1,  45,  12,  14,  84,   8,  61,  77,
        29,  38,  65,  28,  91,  42,  90,  20,  83])

In [5]:
# similar to (note that this changes the array in place):
x = np.arange(1, 101)
np.random.shuffle(x)
x

array([ 80,  62,  91,  14,  20,  66,  82,   6,  45,  23,  77,  60,  96,
        21,  54,  67,  41,  38,  84,  64,  93,  47,  57,  30,  99,  44,
        28,  55,  83,  39,  79,  33,  31,  25,  42,  90,  58,  76,  95,
        48,  11,   2,  50,  69,  52,  71,  94,  75,  49,  40,  85,   4,
        51,  78,   8,   9,  61,  34,  13,  17,  81,  65,  88,  19,  10,
         5,  56,  86,  27,  74,  59,  53,  89,  29,  98,  43,  72,  63,
        24,  36,  15,  32,  97,  87,  73,  46,  22,  35,  70,  92,   7,
        26,  16,  18,  12,  37,   1,   3, 100,  68])

In [6]:
# to reorder x (note that this does not change the array in place)
x = np.sort(x)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
# 20 numbers between 0 and 10
np.random.randint(0, 10, size=20)

array([6, 4, 6, 9, 7, 3, 4, 6, 0, 1, 2, 9, 2, 8, 5, 2, 1, 3, 9, 2])

We can also sample from distributions:

In [8]:
np.random.uniform(low=0, high=10, size=20)

array([6.25281066, 3.59768254, 0.95215574, 8.41004869, 0.65187148,
       8.94067952, 5.31821088, 7.28080722, 9.90525903, 1.55263035,
       6.56004473, 3.33119578, 6.27641887, 1.04621023, 4.33658134,
       6.65110757, 8.21877731, 7.51889882, 4.28735741, 3.91421912])

In [9]:
np.random.normal(loc=0, scale=1, size=10)

array([-1.08386577, -0.33237639, -0.14256541,  1.39712666, -0.63035908,
        0.27859579, -2.43991835, -0.83149125, -0.78916959, -1.16488831])

In [10]:
np.random.normal(loc=[-10, 0, 10], scale=1)

array([-9.13359411, -1.69122744, 10.35144027])

In [11]:
np.random.binomial(n=1, p=.8, size=50)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1])

In [12]:
np.random.binomial(n=1, p=[.6, .8, .1, .2])

array([0, 1, 0, 1])

## 2. Tiling and repeating arrays

In [13]:
letters = np.array(['A', 'B', 'C'])
colors = np.array(['red', 'blue', 'grey'])

In [14]:
colors = np.repeat(colors, repeats=3)
colors

array(['red', 'red', 'red', 'blue', 'blue', 'blue', 'grey', 'grey',
       'grey'], dtype='<U4')

In [15]:
letters = np.tile(letters, reps=3)
letters

array(['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'], dtype='<U1')

In [16]:
colors + letters

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U4'), dtype('<U4')) -> dtype('<U4')

In [17]:
np.char.add(letters, colors)

array(['Ared', 'Bred', 'Cred', 'Ablue', 'Bblue', 'Cblue', 'Agrey',
       'Bgrey', 'Cgrey'], dtype='<U5')

## 3. Creating a pandas dataframe

In [18]:
import pandas as pd

In [19]:
df = pd.DataFrame({
    'letters': letters,
    'colors': colors,
    'stimuli': np.char.add(np.char.add(letters, "_"), colors)
             })

In [20]:
df

letters colors stimuli
0       A    red   A_red
1       B    red   B_red
2       C    red   C_red
3       A   blue  A_blue
4       B   blue  B_blue
5       C   blue  C_blue
6       A   grey  A_grey
7       B   grey  B_grey
8       C   grey  C_grey

In [21]:
df['letters']

0    A
1    B
2    C
3    A
4    B
5    C
6    A
7    B
8    C
Name: letters, dtype: object

In [22]:
df['trial'] = np.arange(1, 10)
df['participant'] = 1

In [23]:
df

letters colors stimuli  trial  participant
0       A    red   A_red      1            1
1       B    red   B_red      2            1
2       C    red   C_red      3            1
3       A   blue  A_blue      4            1
4       B   blue  B_blue      5            1
5       C   blue  C_blue      6            1
6       A   grey  A_grey      7            1
7       B   grey  B_grey      8            1
8       C   grey  C_grey      9            1

In [24]:
df.shape

(9, 5)

In [25]:
df['block'] = 1
df

letters colors stimuli  trial  participant  block
0       A    red   A_red      1            1      1
1       B    red   B_red      2            1      1
2       C    red   C_red      3            1      1
3       A   blue  A_blue      4            1      1
4       B   blue  B_blue      5            1      1
5       C   blue  C_blue      6            1      1
6       A   grey  A_grey      7            1      1
7       B   grey  B_grey      8            1      1
8       C   grey  C_grey      9            1      1

In [26]:
df.loc[(df.trial > 3) & (df.trial < 7), 'block'] = 2
df.loc[df.trial > 6, 'block'] = 3
df

letters colors stimuli  trial  participant  block
0       A    red   A_red      1            1      1
1       B    red   B_red      2            1      1
2       C    red   C_red      3            1      1
3       A   blue  A_blue      4            1      2
4       B   blue  B_blue      5            1      2
5       C   blue  C_blue      6            1      2
6       A   grey  A_grey      7            1      3
7       B   grey  B_grey      8            1      3
8       C   grey  C_grey      9            1      3

## Exercises

- 1 Create a dataframe called `stimuli`. The first column should be called `participant`, the second column `trial`, and the third one `condition`. There should be 10 trials per condition, and 3 conditions for each participant, and 4 participants. Therefore, in total the dataframe should have 4*3*10=120 rows, and 3 columns. The participant numbers should go from 1 to 4, the conditions should be labelled `['low', 'med', 'high']`, and the trials should be numbered from 1 to 30. The order of the condition should be randomized within participant.
- 2 Add a column called `probability`, which is equal to .1 when the condition is `low`, .5 when it's `med`, and .9 when it's 'high'.
- 3 Create a new dataframe called `data`, that is a copy of the `stimuli` dataframe (using the `.copy()` attribute, as in `new_dataframe = old_dataframe.copy()`). Add to `data` a column called `choice`, by generating data from a binomial distribution with parameters `n=1` and the probability that is in the probability column of each trial.

**Send me your solutions** before the end of this Friday (at laura.fontanesi@unibas.ch).

**NOTE**: Do not send me a notebook but export it to a Python script first: `File> Export notebook as… > Export as executable script`